name: test-run
on: pull_request
jobs:
  on-pull-request:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DB_DATABASE: jdbc:mysql://localhost:3306/test_db
      DB_TEST_DATABASE: jdbc:mysql://localhost:3306/test_db
      DB_USERNAME: test_user
      DB_PASSWORD: test_password
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with maven
        run: mvn -e -X clean test